CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE admin.role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE admin.permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE admin.role_permission (
    role_id BIGINT NOT NULL REFERENCES admin.role(id),
    permission_id BIGINT NOT NULL REFERENCES admin.permission(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE admin.subject_role (
    subject_id VARCHAR(40) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES admin.role(id),
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_by VARCHAR(40) NOT NULL,
    PRIMARY KEY (subject_id, role_id)
);

CREATE TABLE admin.audit_log (
    id VARCHAR(36) PRIMARY KEY,
    subject_id VARCHAR(40) NOT NULL,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(120) NOT NULL,
    reason VARCHAR(500),
    trace_id VARCHAR(80) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_admin_audit_subject_occurred
    ON admin.audit_log(subject_id, occurred_at);

INSERT INTO admin.role (code, display_name, created_at) VALUES
    ('SUPER_ADMIN', '超级管理员', CURRENT_TIMESTAMP),
    ('CONTENT_MODERATOR', '内容审核员', CURRENT_TIMESTAMP),
    ('USER_OPERATOR', '用户运营', CURRENT_TIMESTAMP),
    ('AI_OPERATOR', 'AI 运营', CURRENT_TIMESTAMP),
    ('SYSTEM_OPERATOR', '系统运维', CURRENT_TIMESTAMP);

INSERT INTO admin.permission (code, display_name, created_at) VALUES
    ('DASHBOARD_VIEW', '查看运营仪表盘', CURRENT_TIMESTAMP),
    ('CONTENT_MODERATE', '执行内容审核', CURRENT_TIMESTAMP),
    ('USER_GOVERN', '执行用户治理', CURRENT_TIMESTAMP),
    ('AI_OPERATE', '管理提示词、模型路由和 AI 成本', CURRENT_TIMESTAMP),
    ('SYSTEM_OPERATE', '管理媒体任务、通知与系统健康', CURRENT_TIMESTAMP),
    ('RBAC_MANAGE', '管理角色权限', CURRENT_TIMESTAMP),
    ('AUDIT_VIEW', '查看审计日志', CURRENT_TIMESTAMP);

INSERT INTO admin.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM admin.role r CROSS JOIN admin.permission p
WHERE r.code = 'SUPER_ADMIN';

INSERT INTO admin.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM admin.role r JOIN admin.permission p ON p.code IN ('DASHBOARD_VIEW', 'CONTENT_MODERATE')
WHERE r.code = 'CONTENT_MODERATOR';

INSERT INTO admin.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM admin.role r JOIN admin.permission p ON p.code IN ('DASHBOARD_VIEW', 'USER_GOVERN')
WHERE r.code = 'USER_OPERATOR';

INSERT INTO admin.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM admin.role r JOIN admin.permission p ON p.code IN ('DASHBOARD_VIEW', 'AI_OPERATE')
WHERE r.code = 'AI_OPERATOR';

INSERT INTO admin.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM admin.role r JOIN admin.permission p ON p.code IN ('DASHBOARD_VIEW', 'SYSTEM_OPERATE', 'AUDIT_VIEW')
WHERE r.code = 'SYSTEM_OPERATOR';
