CREATE TABLE identity.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    account_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE identity.credential (
    account_id BIGINT PRIMARY KEY,
    password_hash VARCHAR(100) NOT NULL,
    password_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_credential_account
        FOREIGN KEY (account_id) REFERENCES identity.account (id)
);

CREATE TABLE identity.user_session (
    id VARCHAR(36) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_session_account
        FOREIGN KEY (account_id) REFERENCES identity.account (id)
);

CREATE INDEX idx_user_session_account ON identity.user_session (account_id, expires_at);

CREATE TABLE identity.admin_session (
    id VARCHAR(36) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admin_session_account
        FOREIGN KEY (account_id) REFERENCES identity.account (id)
);

CREATE INDEX idx_admin_session_account ON identity.admin_session (account_id, expires_at);
